[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run deploy && npm start"
healthcheckPath = "/api/datasets"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
